---
language: node_js
node_js:
  - "4"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --no-lockfile --non-interactive

script:
  - ember try:each

deploy:
  provider: npm
  email: info@simplabs.com
  api_key:
    secure: q1I/qDa3F+XPIrI1eE0zgBgXtxaBpEM1QMLz4Vcw3ojWJjlUE8lYtulDwsKKuNJ/VDliiymvkiklIGyhQ5NPERwYxmWdMXPORHqxeAARFB3Ylv9wZ7aQv+8hH9l+xm3sKHd5uBW4tMq20ogbqSWFnNRHtvtrqkOkSIOI9cHp29b1xs75rmlbjPAaeZFZJqPsjtAq9pptA6mK83FxIAld7lqPgCGbaJiamT8VujKTXYSMZdHaWAaidzxMmWZnAxUpsUDREa5hx1/jbI0nLnnO4HLWl+MOAwRG877my4AnCDRxUXL0UVSKnN1EQFRflwBP7T8aimL2y5N0gqiABXG7kEtvcBrR2xYC9uyqqRE9PiZB05MuydijuWB77qK63lUB6KIal3uKbjG9sJr9dSCpRCb38nkoRKREd5sCwn6lg4NSoqgWAtz12DsQqd6HgzSEB5uD+IoX3FUuBaldROP2ZL1YsM2unonNF1hMLp0y5U6G714ib9syEi8ZlCFHcVJuNA9NbCx3prXsf2688PyKkFtRy+t5nMCd6jy480lgN3nQBhJo4WXsSOINMQr5GSEMENX3nvx4UdsN4Vo88kJX41P1jDUaLeiJVM2nFXm8QOqN52z3SMemlN56MVWHqfBwq8p4IpWfrFNxVo25+5wccNKFj1sjSR6Zu+dxqSUHIfk=
  on:
    tags: true
    repo: simplabs/ember-validated-form-buffer

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
    on_success: never
